#!/bin/bash

# Quick Production Deployment with Existing Neon Database
echo "🚀 LenoDigital Production Deployment"
echo "====================================="
echo ""

echo "✅ Using existing Neon database for production"
echo "✅ Database schema already deployed"
echo "✅ Demo users already exist in database"
echo ""

echo "📋 NETLIFY ENVIRONMENT VARIABLES TO SET:"
echo "========================================"
echo ""
echo "Go to: https://netlify.com"
echo "Click your 'lenodigital' site"
echo "Go to Site settings → Environment variables"
echo "Add these variables:"
echo ""
echo "DATABASE_URL=postgresql://neondb_owner:npg_bP0lKTQ1EUoR@ep-blue-dust-adpzyffd-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo "NEXTAUTH_URL=https://lenodigital.netlify.app"
echo "NEXTAUTH_SECRET=JHdD8/EOJHmePuBg6QV/1bwzKTfOM04jUrrUbPAFSvU="
echo "APP_URL=https://lenodigital.netlify.app"
echo ""

echo "🎯 DEMO LOGIN CREDENTIALS FOR PRODUCTION:"
echo "========================================"
echo ""
echo "Teacher:"
echo "  Email: sarah.johnson@rivoniaprimary.co.za"
echo "  Password: password123"
echo ""
echo "Student:"
echo "  Email: alex.smith@student.co.za"
echo "  Password: password123"
echo ""
echo "Parent:"
echo "  Email: jane.smith@email.com"
echo "  Password: password123"
echo ""

echo "🚀 DEPLOYMENT STATUS:"
echo "===================="
echo "✅ Code: Pushed to GitHub"
echo "✅ Database: Schema deployed to Neon"
echo "✅ Users: Demo users exist"
echo "❌ Environment: Need to set Netlify variables"
echo ""

echo "📞 NEXT STEPS:"
echo "=============="
echo "1. Set Netlify environment variables (copy above)"
echo "2. Netlify will auto-deploy when you push changes"
echo "3. Test production site with demo credentials"
echo ""

echo "🎉 Ready for production deployment!"
